import React, { useRef } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

type DamageType = "Crack" | "Insect Damage" | "Physical Damage";

interface ReportProps {
  imageUrl: string; // base64 or URL
  damageType: DamageType;
  estimatedCost: number;
  itemsNeeded: string[];
  preventionTips: string[];
  referenceNo: string;
  date: string;
}

const DamageReport: React.FC<ReportProps> = ({
  imageUrl,
  damageType,
  estimatedCost,
  itemsNeeded,
  preventionTips,
  referenceNo,
  date,
}) => {
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = async () => {
    if (reportRef.current) {
      const canvas = await html2canvas(reportRef.current);
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save(`FurniScan_Report_${referenceNo}.pdf`);
    }
  };

  return (
    <div>
      <div
        ref={reportRef}
        style={{
          width: "600px",
          padding: "24px",
          background: "#fff",
          color: "#222",
        }}
      >
        <h2 style={{ textAlign: "center" }}>Wooden Furniture Damage Report</h2>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginBottom: 16,
          }}
        >
          <span>Date: {date}</span>
          <span>Ref No: {referenceNo}</span>
        </div>
        <div style={{ textAlign: "center", marginBottom: 16 }}>
          <img
            src={imageUrl}
            alt="Uploaded"
            style={{ maxWidth: "100%", maxHeight: 300 }}
          />
        </div>
        <div>
          <strong>Identified Damage Type:</strong> {damageType}
        </div>
        <div>
          <strong>Estimated Repair Cost:</strong> LKR{estimatedCost.toFixed(2)}
        </div>
        <div>
          <strong>Possible Items Needed:</strong>
          <ul>
            {itemsNeeded.map((item, idx) => (
              <li key={idx}>{item}</li>
            ))}
          </ul>
        </div>
        <div>
          <strong>Prevention Tips:</strong>
          <ul>
            {preventionTips.map((tip, idx) => (
              <li key={idx}>{tip}</li>
            ))}
          </ul>
        </div>
        <div style={{ marginTop: 24, fontSize: 12, textAlign: "center" }}>
          Generated by FurniScan AI | www.furniscan.com
        </div>
      </div>
      <button onClick={handleDownloadPDF} style={{ marginTop: 16 }}>
        Download PDF Report
      </button>
    </div>
  );
};

export default DamageReport;
